### ISSUE TITLE
Getting RecipeFetchException and NoSuchFileException when I try to install recipe

### ISSUE THREAD

**Issue by biot023** [LoopPerfect/buckaroo#100]
Hi -- I followed the install instructions for Buck and Buckaroo, but my setup is failing when I try to install a recipe. The install command I'm using is this:

    $ buckaroo install ericniebler/range-v3

This gives me this error:

> Error!                                                                          
> com.loopperfect.buckaroo.sources.RecipeFetchException: Could not fetch ericniebl
> er/range-v3                                                                     
> java.nio.file.NoSuchFileException: /home/douglivesey/.buckaroo/buckaroo-recipes/
> recipes/ericniebler/range-v3.json                                               

If I try with another recipe, I get the same thing, for example:

    $ buckaroo install philsquared/catch

Gives me the error:

> Error!                                                                          
> com.loopperfect.buckaroo.sources.RecipeFetchException: Could not fetch philsquar
> ed/catch                                                                        
> java.nio.file.NoSuchFileException: /home/douglivesey/.buckaroo/buckaroo-recipes/
> recipes/philsquared/catch.json                                                  

The directory `/home/douglivesey/.buckaroo` exists with the files `buckaroo.json` and `user-uuid.txt` in it. The subdirectory `buckaroo-recipes` doesn't exist in there, but explicitly creating it doesn't fix the problem.

I'm running Ubuntu 17.04.

Thanks for any and all advice you can offer to help me fix this.
   Doug.

**Comment by njlr** [comment]
Hi Doug, 

Sorry that you have run into this issue! I will try to reproduce it now.

**Comment by njlr** [comment]
Hi Doug,

Sorry that you have run into this issue! I will try to reproduce it now.

**Comment by njlr** [comment]
Yes, this is indeed a bug! Buckaroo is not fetching the cookbook correctly on start-up. 

For now, you can just fetch it manually: 

```bash=
buckaroo update
```

After you do this `buckaroo install` commands should work.

**Comment by biot023** [comment]
Yep, that seems to have fixed the issue -- cheers @njlr !

**Comment by njlr** [comment]
Glad it works! Issue for doing this automatically here... https://github.com/LoopPerfect/buckaroo/issues/101
