### ISSUE TITLE
Install from a Git branch

### ISSUE THREAD

**Issue by nikhedonia** [LoopPerfect/buckaroo#107]

**Comment by njlr** [comment]
This would be really nice, but there are a few complexities that arise: 

 * We would need to move away from just sem-ver as project versions and support commits along a branch. Like sem-ver this is effectively a track with ordered milestones on it, so an abstraction should be possible
 * We would need to decide how resolution would work - can you depend on "this commit and greater", for example?

**Comment by njlr** [comment]
Related to https://github.com/LoopPerfect/buckaroo/issues/132 since both will involve creation of version-pairs
