### ISSUE TITLE
Timeout download library

### ISSUE THREAD

**Issue by nicht** [LoopPerfect/buckaroo#110]
When i try to run for example: `buckaroo install boost/locale` it gave me this error.  
```
Download error!                                                                 
There was an error downloading a file.                                          
 * URL:                                                                         
   https://raw.githubusercontent.com/njlr/typeof/360bfb1315950104951f68e66cfb9ba
 * Target: /home/nicht/Dev/Merlin/Merlin/buckaroo/official/boost/typeof/BUCK    
 * Cause:                                                                       
   java.net.SocketException: Connection reset                                   
```

EDIT: Wrong error message.

**Comment by nikhedonia** [comment]
Thanks for creating  this issue. 
If I read you correctly, your issue is about the error message. 
Installing `boost/locale` works correctly with an existing and stable internet connection, is that correct ?
Any suggestions how to improve the error message?

**Comment by nicht** [comment]
Wellp, not actually the error message. But i figured out that was because my connection was unstable.
