### ISSUE TITLE
Archive formats other than zip?

### ISSUE THREAD

**Issue by isundaylee** [LoopPerfect/buckaroo#128]
Some libraries (e.g. minilzo http://www.oberhumer.com/opensource/lzo/) only provide official .tar.gz archives. Currently, according to the documentation, it sounds like the recipe system only supports .zip archives. 

1. Is that true? 
2. If so, any recommendation of workarounds? I guess one would be to self-host the files on GitHub, but that sounds a bit sketchy...

**Comment by njlr** [comment]
1. Yes, only `.zip` is currently supported
 2. Self-host on GitHub would be one work-around

Does that library provide a Git repo? That would probably be the best solution for Buckaroo as it works now.

**Comment by isundaylee** [comment]
No it doesn't.. It's a pretty old library. I guess the self-host solution is a decent work-around. So I'm closing this for now :)
