### ISSUE TITLE
Overwriting .buckconfig.local

### ISSUE THREAD

**Issue by isundaylee** [LoopPerfect/buckaroo#130]
Is it the current expected behavior for Buckaroo to overwrite .buckconfig.local every time we do `buckaroo install` or the like? Personally I use .buckconfig.local to set machine-specific options (e.g. path to clang++, etc.). What do you think of letting Buckaroo merge its content with the existing .buckconfig.local instead of overwriting it? I can probably work on a PR if you think this is worth having.

**Comment by njlr** [comment]
Yes this is how it works at the moment, which, as you have noticed, is not a very good solution. 

For background, the reason that we need to modify the .buckconfig is to write the cell names (repositories tag), and maybe additional content in the future. 

I like the merge idea but it might be tricky to implement in practice. How would we distinguish user content from content that buckaroo generated previously?

One solution that avoids this problem would be to have another config file (.buckconfig.local.user?) that is read by buckaroo to generate the real .buckconfig.local. The downside is this deviates from how Buck works by default. 

Another solution would to overwrite content that Buckaroo needs to set (repositories only atm) and copy the rest. The task would then be to write a simple .ini parser (or use Buck‘s), read the file, update the tags and write back the file. 

Maybe there is a feature of Buck I'm not aware of that can help here? I saw in your repo several .buckconfig files. What do you think?

**Comment by isundaylee** [comment]
@njlr  Those `.buckconfig` files are the unfortunate by-product of the time when I did not know about flavors.. To use them you need to explicitly specify like `buck build @.buckconfig.release :main`

One thing we can potentially try is to surround Buckaroo-generated part of `.buckconfig.local` with something like: 

```
# BUCKAROO_START
# Generated by Buckaroo. Please do not touch.
[repositories]
  nlohmann.json = buckaroo/official/nlohmann/json
  jarro2783.cxxopts = buckaroo/official/jarro2783/cxxopts
  weidai11.cryptopp = buckaroo/official/weidai11/cryptopp
  github.isundaylee.minilzo = buckaroo/github/isundaylee/minilzo
# BUCKAROO_END
```

This would allow us to separate Buckaroo-generated portion and user-generated portion, and merge accordingly.

**Comment by njlr** [comment]
Another solution would be to introduce another `.buckconfig` for generated values (`.buckconfig.auto`?). This would be a change to Buck, not Buckaroo. The precedence order would be: 

 * `.buckconfig`
 * `.buckconfig.auto`
 * `.buckconfig.local`

Buck should already have the merging logic implemented for `.buckconfig` + `.buckconfig.local`. 

I like this solution because it does not interfere with the work-flow of Buck when not using Buckaroo. 

@nikhedonia ?

**Comment by njlr** [comment]
I will work on parsing + manipulating the `.buckconfig(.local)`.
