### ISSUE TITLE
Buckaroo website is down

### ISSUE THREAD

**Issue by ogranada** [LoopPerfect/buckaroo#140]
Buckaroo website is down

## Description

Buckaroo website show message `Service Temporarily Unavailable`

## Expected Behavior

Page should render to list available packages.

## Actual Behavior

Show an error message.

**Comment by nikhedonia** [comment]
@ogranada we are migrating our servers to another cloud provider, we'll be online again by monday

**Comment by mdrost** [comment]
Which Monday? :P

**Comment by nikhedonia** [comment]
ssl is still broken, but the page is  already accessible over http
http://buckaroo.pm/
