### ISSUE TITLE
Failed to install dependency from GitHub

### ISSUE THREAD

**Issue by 3mbd3v** [LoopPerfect/buckaroo#141]
## Description
When I'm trying to install dependency from GitHub, I get user authentication fail. Tried with `buckaroo install github+loopperfect/neither` and with my own library.

## Expected Behavior
Successful installation of dependency.

## Actual Behavior
`buckaroo install github+loopperfect/neither` returns:
`Error!                                                                          
com.loopperfect.buckaroo.sources.RecipeFetchException: Could not fetch github+lo
opperfect/neither                                                               
git@github.com:loopperfect/neither.git: USERAUTH fail`

## Possible Fix
Use https to clone instead of ssh.

## Steps to Reproduce
1. mkdir test && cd test
2. buckaroo quickstart
3. buckaroo install github+loopperfect/neither

## Your Environment
* Version used: 1.3.1
* Operating System and Architecture: Linux, Ubuntu 16.04 amd64

**Comment by njlr** [comment]
Buckaroo communicates with Git using SSH rather than HTTPS. This is because we have not implemented the HTTPS password-entry step yet. 

Perhaps the GitHub identity has not been added to SSH yet?

You can check by doing an SSH clone: 

```bash=
git clone git@github.com:LoopPerfect/neither.git
```

Follow any prompts Git gives you, then retry.

**Comment by 3mbd3v** [comment]
SSH clone of neither library works fine:
`git clone git@github.com:LoopPerfect/neither.git` returns:
>Cloning into 'neither'...
>remote: Counting objects: 285, done.
>remote: Compressing objects: 100% (20/20), done.
>remote: Total 285 (delta 8), reused 14 (delta 5), pack-reused 260
>Receiving objects: 100% (285/285), 43.82 KiB | 359.00 KiB/s, done.
>Resolving deltas: 100% (137/137), done.

Using buckaroo install with github+<PACKAGE_NAME> still returns same error.

I've also cloned buckaroo repository and build it with buck. After running `buck test :buckaroo-integration` I get result (last lines of it):

> TESTS FAILED: 15 FAILURES
> Failed target: //:buckaroo-integration
> FAIL com.loopperfect.buckaroo.bitbucket.BitBucketGitProviderTest
> FAIL com.loopperfect.buckaroo.github.AsyncDependencyResolverTest
> FAIL com.loopperfect.buckaroo.github.GitHubGitProviderTest
> FAIL com.loopperfect.buckaroo.gitlab.GitLabGitProviderTest
> FAIL com.loopperfect.buckaroo.tasks.CacheTasksTest
> FAIL com.loopperfect.buckaroo.tasks.DownloadTaskTest
> FAIL com.loopperfect.buckaroo.tasks.GitTasksTest
> FAIL com.loopperfect.buckaroo.tasks.InstallTasksTest

Running integration tests is mentioned in Readme, but in travis there is only build job for buckaroo-integration without calling tests. Is there any reason that those tests aren't run on travis or is it only oversight?

**Comment by njlr** [comment]
The integration tests depend on external services, not just the code of Buckaroo, so we didn't want to make them a blocker for pull requests. We keep them because they can be useful for diagnosing issues.

I'm surprised that an SSH clone works but Buckaroo does not. I will have to investigate it further...

**Comment by njlr** [comment]
What output do you get for a direct SSH connection? 

```
$ ssh -T git@github.com
Hi njlr! You've successfully authenticated, but GitHub does not provide shell access.
```

See also: [https://help.github.com/articles/testing-your-ssh-connection/](https://help.github.com/articles/testing-your-ssh-connection/)

**Comment by 3mbd3v** [comment]
Same response as yours:
```
$ ssh -T git@github.com
Hi 3mbd3v! You've successfully authenticated, but GitHub does not provide shell access.
```

Tested also on another machine with fresh installation of Ubuntu 17.10 with same result. Currently I don't have access to any Windows machine to test on it.

**Comment by 3mbd3v** [comment]
Ok, I've tested some combinations and installation works when I have not encrypted my private key. Temporarily this may work for me, because I can store my key on encrypted partition, but it is not solution of the problem - I don't think anyone would like to use key without passphrase.

**Comment by njlr** [comment]
Buckaroo Redux will leverage the Git CLI, so will be more likely to work with custom setups.

**Comment by njlr** [comment]
Fixed in Buckaroo Redux.
