### ISSUE TITLE
Failed to install buckaroo

### ISSUE THREAD

**Issue by Adiqq** [LoopPerfect/buckaroo#142]
## Description

Buckaroo installation fails on Arch Linux.
## Expected Behavior

Buckaroo installs correctly.
## Actual Behavior

https://gist.github.com/Adiqq/c0f5ba4b5813e38654510df5ea4b00ad
## Steps to Reproduce

1. Clone https://github.com/Adiqq/buckaroo
2. Ensure docker is installed. Run `docker build -t buckaroo .`

## Context

Cannot use backaroo. Trying to install it.
## Your Environment

* Version used:
* Operating System and Architecture: Docker base/archlinux and actual Arch Linux

**Comment by nikhedonia** [comment]
Looks like homebrew fails to install buck. I'll have a closer look tomorrow

**Comment by roxma** [comment]
Same issue here

```
Updating Homebrew...
==> Installing buckaroo@1.3.1 from loopperfect/lp
==> Installing dependencies for loopperfect/lp/buckaroo@1.3.1: buck
==> Installing loopperfect/lp/buckaroo@1.3.1 dependency: buck
==> Downloading https://api.github.com/repos/facebook/buck/tarball/v2017.10.01.01
Already downloaded: /home/roxma/.cache/Homebrew/buck-2017.10.01.01.01
==> ant
Last 15 lines from /home/roxma/.cache/Homebrew/Logs/buck/01.ant:
    [javac]      ^^^^^^^^
    [javac] Override cannot be resolved to a type
    [javac] ----------
    [javac] 2903. ERROR in /tmp/buck-20171106-20076-ec4bg8/facebook-buck-2025fd7/third-party/java/aosp/src/com/android/manifmerger/XmlNode.java (at line 301)
    [javac]     @Override
    [javac]      ^^^^^^^^
    [javac] Override cannot be resolved to a type
    [javac] ----------
    [javac] 2903 problems (2903 errors)

BUILD FAILED
/tmp/buck-20171106-20076-ec4bg8/facebook-buck-2025fd7/build.xml:351: The following error occurred while executing this line:
/tmp/buck-20171106-20076-ec4bg8/facebook-buck-2025fd7/build.xml:395: Compile failed; see the compiler error output for details.

Total time: 6 seconds

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/facebook/homebrew-fb/issues
```


The key message from  /home/roxma/.cache/Homebrew/Logs/buck/01.ant is:

```
    [javac] Annotation processing got disabled, since it requires a 1.6 compliant JVM
```

Linuxbrew uses java 1.9, and it is somehow incompatible with the build system. Although this is not buckaroo's issue, linuxbrew is the only way for installing buckaroo on my system.

Is there anyway I can workaround this?

**Comment by roxma** [comment]
Reported to https://github.com/facebook/buck/issues/1611

**Comment by roxma** [comment]
Unfortunately linuxbrew doesn't provide older jdk version, my current workaround is to remove the jdk links in ~/.linuxbrew/bin

```
cd ~/.linuxbrew/bin/
echo mv $(ls -l |  grep jdk | awk '{print $9}') backupdir/
```

**Comment by roxma** [comment]
Well, my current workaround is to install it from source.  I removed the linuxbrew installation.

It works just fine with jdk 1.8.

**Comment by njlr** [comment]
The preferred way to install Buck & Buckaroo on Linux is to use Debian packages. 

See here for an example: 
https://github.com/LoopPerfect/buckaroo/blob/efab3f31006fcfcc1375cc0511e25027e72e3b55/.travis.yml#L5
