### ISSUE TITLE
Package installation errror

### ISSUE THREAD

**Issue by nkrambo** [LoopPerfect/buckaroo#143]
Not sure if this is a buckaroo issue.

I get the following error trying to install any package.

"Error! java.lang.NullPointerException"

It does update the buckaroo.json with the new deps, however.

I'm using buckaroo 1.3.1.
macOS highSierra 10.13.1
java 9.0.1
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

Stack Trace:

com.loopperfect.buckaroo.EvenMoreFiles.lambda$switchFileSystem$1(EvenMoreFiles.java:198)
java.base/java.util.stream.ReduceOps$1ReducingSink.accept(ReduceOps.java:80)
java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:486)
com.loopperfect.buckaroo.EvenMoreFiles.switchFileSystem(EvenMoreFiles.java:196)
com.loopperfect.buckaroo.EvenMoreFiles$CopyFileVisitor.preVisitDirectory(EvenMoreFiles.java:181)
com.loopperfect.buckaroo.EvenMoreFiles$CopyFileVisitor.preVisitDirectory(EvenMoreFiles.java:147)
java.base/java.nio.file.Files.walkFileTree(Files.java:2720)
java.base/java.nio.file.Files.walkFileTree(Files.java:2785)
com.loopperfect.buckaroo.EvenMoreFiles.copyDirectory(EvenMoreFiles.java:141)
com.loopperfect.buckaroo.EvenMoreFiles.unzip(EvenMoreFiles.java:123)
com.loopperfect.buckaroo.tasks.CommonTasks.lambda$unzip$10(CommonTasks.java:137)
io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:35)
io.reactivex.Single.subscribe(Single.java:2703)
io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:299)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
java.base/java.lang.Thread.run(Thread.java:844)

**Comment by njlr** [comment]
I haven't come across this problem before, but I am using a different version of Java: 

```
java -version
java version "1.8.0_92"
```

I'm curious if Buck works with Java 9 anyway? They created an issue here: https://github.com/facebook/buck/issues/1548

Is it possible for you to stick to Java 8? If not, I can investigate further.

**Comment by nkrambo** [comment]
Thanks @njlr.

Good question. Yeah I can downgrade Java easily enough. I'll let you know how it goes with 8.
