### ISSUE TITLE
is this repo dead?

### ISSUE THREAD

**Issue by mathiasgrimm** [LoopPerfect/buckaroo#152]
I liked the idea and was planning to use it in a project but as per github, the last commit is from 4 months ago and I wonder if the development has ceased
tks

**Comment by nikhedonia** [comment]
No it is not dead yet. Development will be resumed in July. We have been putting our resources in  research. We will share our results soon and we will be probably introducing architectural changes.

**Comment by thoughton** [comment]
Ah man, this is a bit disheartening. I got pretty excited about the project when I first read all those Hacker Noon articles about it a few months ago, and like the OP I was just starting a project using it the other day - and then I found this issue, and I'm worried now about what the future of the project might be. Please don't wait too long before sharing your plans!

**Comment by Dwood15** [comment]
For anyone that wants to talk package management development, I invite you to: https://discord.gg/P3vtVSE

There's a (currently empty) channel already waiting buckaroo talk.

**Comment by nikhedonia** [comment]
Work has been resumed.
Goals and roadmap of buckaroo will be published soon.

**Comment by njlr** [comment]
So we need to do a proper announcement, but here are the key points: 

 - Buckaroo has funding for 2 developers full-time for approximately 1 year
 - We have an automated build-system porting tool at an alpha stage (see https://hackernoon.com/announcing-buildinfer-for-c-3dfa3eb15feb)
 - Full roadmap to follow
