### ISSUE TITLE
Build exits before completion

### ISSUE THREAD

**Issue by fishsirc** [LoopPerfect/buckaroo#167]
Buckaroo build on Windows 10 exists before it finished
## Description

No buckaroo-cli.jar created when running **buck build :buckaroo-cli** on Windows 10, Python 27, java version "1.8.0_181".
## Expected Behavior

buckaroo-cli.jar should be created under _buck-out_ directory
## Actual Behavior

build exits after it reached step 59 out from 66, instead of fully building **buckaroo**, 
## Steps to Reproduce

run command **buck build :buckaroo-cli** on Windows 10 in GitBash

## Context

Use **buckaroo** on Windows 10
## Your Environment

* Version used: Tried different versions of buckaroo: v1.3.1, v1.4.0
* Operating System and Architecture: Windows 10, Python 27, java 1.8.0_181

**Comment by njlr** [comment]
Hi @fishsirc, thanks for taking the time to report this issue! 

I do not have access to a Windows machine right now, but we do have an [Appveyor CI build that succeeds](https://ci.appveyor.com/project/njlr/buckaroo). Perhaps that can give some hints? 

In the mean-time, I suggest fetching the prebuilt jar from the releases page: https://github.com/LoopPerfect/buckaroo/releases/tag/v1.4.0

**Comment by njlr** [comment]
With Buckaroo Redux we provide a Warp bundle for Windows https://github.com/LoopPerfect/buckaroo/issues/238
