### ISSUE TITLE
Executable packages

### ISSUE THREAD

**Issue by abranhe** [LoopPerfect/buckaroo#176]
It would be great to be able to add/install executable packages to your path using **buckaroo**. We use daily cli tools for building software. Having a package manager that will help you integrate those tools easily would be amazing.

It would be the same idea of installing package globally of npm: `npm install --global pkg`

We can approch this by adding a new property on the buckaroo recipies (`buckaroo.json` file).

###### `buckaroo.json`

```json
{
 "script": "buck run :main" 
}
```

Then by installing a buckaroo library

```
$ buckaroo i user/pkg
```

If it identify the `script` property on the `buckaroo.json` file it automatically install it on your path.

This is just a picture of a basic idea, but personally I think it would be great.

**Comment by njlr** [comment]
This is already supported, but not in _quite_ the same way as NPM / Yarn. 

As you have probably seen, Buck has a concept of genrules (https://buckbuild.com/rule/genrule.html). A genrule can call the output of another target as an executable. It looks a bit like this: 

```python=
genrule(
  name = 'thing', 
  out = 'thing.txt', 
  cmd = '$(exe :thing-generator) > $OUT', 
)
```

So the program `thing-generator` is called to create `thing.txt`, and `thing-generator` can come from a package. 

There is an example of this here: https://github.com/njlr/buckaroo-test-google-protobuf/blob/61625b52bd23f5d0d9264a20aa25fb17c51ba814/BUCK#L20

**Comment by njlr** [comment]
This is now documented here https://github.com/LoopPerfect/buckaroo/wiki/Executable-Packages
