### ISSUE TITLE
buckaroo uninstall doesn't remove source code

### ISSUE THREAD

**Issue by kindlychung** [LoopPerfect/buckaroo#177]
## Description
buckaroo uninstall doesn't remove source code

## Expected Behavior
when executing `buckaroo uninstall some-dep`, i expect `buckaroo/github/user/some-dep` to be removed.

## Actual Behavior
`buckaroo/github/user/some-dep` is not removed.

## Possible Fix
probably just add a line of code to remove the dep folder.

## Steps to Reproduce

1. `mkdir test && cd test && buckaroo quickstart`
2. `buckaroo install github+kindlychung/buckaroo-github-example`
3. `buckaroo uninstall github+kindlychung/buckaroo-github-example`
4. `ls buckaroo/github/kindlychung/buckaroo-github-example/`

## Context
i was just trying to remove a dependency.

## Your Environment

* Version used: 1.4.1
* Operating System and Architecture:
* ubuntu 18.10
* open jdk 8

**Comment by njlr** [comment]
Hmm interesting! 

It does look like the package is removed from the dependencies list:

```bash=
$ cat BUCKAROO_DEPS 
# Generated by Buckaroo, do not edit! 
# This file should not be tracked in source-control. 
BUCKAROO_DEPS = [
]
```

And also the `.buckconfig` has been updated: 

```bash=
$ cat .buckconfig 
[repositories]

```

So the project will build correctly, but we should clean up the `buckaroo` folder also. 

@abranhe would you be interested in picking this up?

**Comment by njlr** [comment]
In Buckaroo Redux this is a feature. 

We will add functionality to prune packages in a seperate command: https://github.com/LoopPerfect/buckaroo/issues/282
