### ISSUE TITLE
buckaroo upgrade doesn't upgrade source code

### ISSUE THREAD

**Issue by kindlychung** [LoopPerfect/buckaroo#178]
## Description
buckaroo upgrade doesn't upgrade source code

## Expected Behavior
when executing `buckaroo upgrade some-dep`, i expect `buckaroo/github/user/some-dep` to be upgraded to the latest release.

## Actual Behavior
`buckaroo/github/user/some-dep` is not upgraded.

## Steps to Reproduce

1. `mkdir test && cd test && buckaroo quickstart`
2. `buckaroo install github+kindlychung/buckaroo-github-example`
2. change kindlychung/buckaroo-github-example and publish a new release
2. change `buckaroo.json` so the version number is set to `*`.
3. `buckaroo upgrade`
4. `cat buckaroo/github/kindlychung/buckaroo-github-example/sum.hpp` to see that the content of this source file is not synced to the latest release.

## Context
i was just trying to upgrade a dependency.

## Your Environment

* Version used: 1.4.1
* Operating System and Architecture:
* ubuntu 18.10
* open jdk 8

**Comment by njlr** [comment]
I just tested it, and it look like `buckaroo.lock.json` is updated but the `buckaroo` folder is not. This is definitely a bug. 

Work-around: 

```bash=
buckaroo upgrade
rm -rf ./buckaroo
buckaroo install
```

Buckaroo has a global cache, so it shouldn't take too long to re-install.

**Comment by njlr** [comment]
Fixed in Buckaroo Redux
