### ISSUE TITLE
License of subdir_glob.bzl

### ISSUE THREAD

**Issue by trittweiler** [LoopPerfect/buckaroo#312]
What is the license of the subdir_glob.bzl file that you use in the recipes and pre-made forks?

E.g. https://github.com/buckaroo-pm/fmt/blob/9dbe606176a43342b04eb6feb87d72d6aace07be/subdir_glob.bzl

**Comment by njlr** [comment]
It is from the documentation of Buck, so `Apache-2.0` https://github.com/facebook/buck/blob/master/LICENSE

**Comment by trittweiler** [comment]
I couldn't find it anywhere in the docs of Buck, though.

The implementation is part of the source file [python-dsl/buck/buck_parser/buck.py](https://github.com/facebook/buck/blob/074240a177b55b4bc1c1c9e53825142413750ae0/python-dsl/buck_parser/buck.py#L576) in the buck git repository. Which is indeed licensed under Apache-2.0.

Thanks for your pointer. I will close the issue.
