### ISSUE TITLE
Buckaroo Docs Website

### ISSUE THREAD

**Issue by abrahamcalf** [LoopPerfect/buckaroo#313]
I saw the new structure of the Buckaroo project, you guys moved all the documentation to the wiki page. I think that's alright but I decided to create a website for the Buckaroo Documentation.

[<img width="1373" alt="screenshot" src="https://user-images.githubusercontent.com/21347264/52618091-d74c7000-2e6b-11e9-9f91-718204899560.png">](https://buckaroo.netlify.com/)

Check it out https://buckaroo.netlify.com/ and share your thoughts.

was created with [Docusaurus](https://docusaurus.io/) (a Facebook project to create documentation websites build on React). The demo is hosted on [Nelify](https://netlify.com) and I really recommend to publish it there, and it will be nice to have the Buckaroo documentation at https://docs.buckaroo.pm as I wrote on the [Documentation website blog](https://buckaroo.netlify.com/blog/#documentation-website).

[<img width="1171" alt="shot" src="https://user-images.githubusercontent.com/21347264/52618462-e67fed80-2e6c-11e9-8459-d597802820d0.png">](https://buckaroo.netlify.com/blog/#documentation-website)

**Repository**: https://github.com/abranhe/buckaroo-docs

**Comment by nikhedonia** [comment]
@abranhe this is amazing! We are really blown away by your initiative!
Unfortunately we didn't expect your contribution and it just happen that we deployed a new page just today.

We will try to be more transparent about the things we are working on.

**Comment by abranhe** [comment]
@nikhedonia it looks great, but the page you guys upload it is not up to know a documentation page as I appreciate.

This website [buckaroo.netlify.com/docs](https://buckaroo.netlify.com/docs/installation) already have the documentation created, and it was written in [pure mardown](https://github.com/abranhe/buckaroo-docs/tree/master/docs), so it is easier to write documentation.

And it don't need to be on the root website (https://buckaroo.pm) it would be great to have it at https://docs.buckaroo.pm

**Comment by njlr** [comment]
The code for the blog and landing page is here: https://github.com/buckaroo-pm/buckaroo-pm.github.io

Would it be possible to integrate the Docusaurus docs pages into this? Or alternatively integrate that into Docusaurus?
