### ISSUE TITLE
Trim identifiers entered at the command line

### ISSUE THREAD

**Issue by njlr** [LoopPerfect/buckaroo#32]

**Comment by hvze** [comment]
What qualifies as an identifier?

**Comment by njlr** [comment]
An identifier is valid if it passes this test: 

```
x.length() > 1 && x.length() < 31 && x.matches("^[a-zA-Z]+[a-zA-Z0-9-_+]*$");
```
([source-code](https://github.com/LoopPerfect/buckaroo/blob/master/src/main/java/com/loopperfect/buckaroo/Identifier.java))

In English: 
- At least one character long
- No more than 30 characters long
- Must start with a letter
- May contain numbers, `-`, `_` or `+`
- Upper-case and lower-case are allowed

Some examples can found [in the unit-tests](https://github.com/LoopPerfect/buckaroo/blob/master/src/test/java/com/loopperfect/buckaroo/IdentifierTest.java). 

We try to follow `this-naming-convention` in the official cook-book.

**Comment by njlr** [comment]
(Added an [issue on the docs](https://github.com/LoopPerfect/buckaroo-docs/issues/5) for this)

**Comment by hvze** [comment]
Well, what do you mean by 'trim'?

**Comment by njlr** [comment]
In the CLI the user may enter an identifier surrounded by white-space. In this case, we should trim the input before checking if the identifier is valid.
