### ISSUE TITLE
Add/Fix support for gitlab subprojects

### ISSUE THREAD

**Issue by nikhedonia** [LoopPerfect/buckaroo#322]
The parser currently does not support subprojects as it expects exactly two `/`.
`gitlab.com/just-a-framework/libraries/std-port@branch=master`

**Comment by njlr** [comment]
GitLab can nest projects in subfolders to an arbitrary depth. We need to expand the data-structure and parser to support this. 

Regular old `org/project` style URLs continue to work.

**Comment by njlr** [comment]
WIP https://github.com/LoopPerfect/buckaroo/tree/bugfix/322

**Comment by njlr** [comment]
https://github.com/LoopPerfect/buckaroo/pull/324
