### ISSUE TITLE
Cannot run buckaroo: "No such file or directory"

### ISSUE THREAD

**Issue by ngriffiths** [LoopPerfect/buckaroo#338]
## Description
When I run `buckaroo quickstart` (or any other command) I see the following message:
```
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

I followed the [installation instructions](https://github.com/LoopPerfect/buckaroo/wiki/Installation) to install buckaroo 2.2.0 (using wget) and buck 2019.01.10.01 (using homebrew).

## Your Environment
```
$ uname -a
Darwin Nicks-MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
```

**Comment by njlr** [comment]
I cannot reproduce this on Linux, will try macOS.

**Comment by njlr** [comment]
I did a clean install on macOS and did not hit this issue. 

To me this looks like a Warp issue. 

Please could you try clearing you Warp cache folder? 

```bash
rm -rf ~/Library/Application\ Support/warp
```

**Comment by ngriffiths** [comment]
That did the trick, thanks!

**Comment by njlr** [comment]
Awesome! :tada:
