### ISSUE TITLE
C support

### ISSUE THREAD

**Issue by cup** [LoopPerfect/buckaroo#339]
Does this project work with C? If so I think it should be explicitly mentioned here:

https://github.com/LoopPerfect/buckaroo

rather than just saying "and friends".

**Comment by nikhedonia** [comment]
Buckaroo support any language that [Buck](https://buckbuild.com) supports.
This includes: 
Asm, C, C++, Obj-C++, CUDA, D, Go, Groovy, Halide, Haskell, Java, Kotlin, Swift, Lua, OCaml, Rust, C# 

However so far most of our users are using buckaroo for C/C++ Projects and as a result we ended up with more than 350 C/C++ packages.

The [Cppslack](https://cpplang.slack.com) community recently crowdsourced a [comparison of build-systems](https://docs.google.com/document/d/1y5ZD8ETyGtxCmtT9dIMDTnWwbeg-HCpLkNiFJPO4Rdw/edit#) showing why buck is an extraordinary good fit for C/C++ and other languages.

**Comment by cup** [comment]
@nikhedonia thanks for great response!
