### ISSUE TITLE
Depedency unresolvably

### ISSUE THREAD

**Issue by Tombert** [LoopPerfect/buckaroo#343]
When I try adding the protobuf-c library, I get the error that the library is unresolvable.  

## Description

I want to add the library "protobuf-c" to my project, but when I do I get the "unresolvable" error

## Expected Behavior
Adding the library to the manifest

## Actual Behavior
Adding library fails

## Steps to Reproduce

```
➜   buckaroo add github.com/protobuf-c/protobuf-c@branch=master
info Adding dependency on github.com/protobuf-c/protobuf-c at branch=master
[solver] info Trying github.com/buckaroo-pm/ericniebler-range-v3 at branch=master
[git] info Fetching refs from https://github.com/protobuf-c/protobuf-c.git
[git] success Fetched 15 refs in 0.191
[solver] warning Unresolvable: github.com/protobuf-c/protobuf-c@branch=master
[git] info Fetching refs from https://github.com/buckaroo-pm/ericniebler-range-v3.git
[git] success Fetched 49 refs in 0.123
error Failed to add the dependency

```

## Context

I need to use regular C for this project (not C++), and I was hoping to use this to manage the protobuf C library.

## Your Environment
Ubuntu Linux 18.10, AMD Ryzen CPU, zsh,
 
```
gcc --version
gcc (Ubuntu 8.2.0-7ubuntu1) 8.2.0
```

```
➜   buckaroo version  
2.2.0
```

**Comment by njlr** [comment]
Hi @Tombert 

It looks like there is no `buckaroo.toml` file in `github.com/protobuf-c/protobuf-c` at `master`.

**Comment by Tombert** [comment]
Ah, I was under the erroneous impression that buckaroo would work on random C libraries doing some kind of chroot thing or something...Clearly I was mistaken!

Thanks for your help.  Looks like I'll need to either fork protobuf-c  and add the buckaroo config or figure out another way to do what I need.

**Comment by njlr** [comment]
Yes unfortunately there is no magic solution! 

We did consider a `chroot` approach but this would not work on Windows and doesn't benefit from remote caching. 

> Thanks for your help. Looks like I'll need to either fork protobuf-c and add the buckaroo config or figure out another way to do what I need.

Yes this is correct. Let me know if you get stuck.

**Comment by Tombert** [comment]
I don't consider not working on Windows to be a bug :) 

Anyway, I think I have an idea on how to do it with a chroot on my Raspberry Pi.  Thanks for your help, you can feel free to close the issue.
