### ISSUE TITLE
code not displaying correctly in Hackernoon articles

### ISSUE THREAD

**Issue by mackuba** [LoopPerfect/buckaroo#361]
Hey, sorry, I couldn't find a better way to contact you.

I tried to read this article yesterday: https://hackernoon.com/common-misconceptions-of-c-4f49f36b92a, but it seems that all code samples are displaying as... an avatar image. It seems to be this way in other articles too. I see this in Safari, Chrome and on iPhone. Can you check what's wrong there?

**Comment by njlr** [comment]
Yes, I am seeing the same issue. It looks like Medium has broken something.

**Comment by njlr** [comment]
This link still works correctly: https://medium.com/hackernoon/common-misconceptions-of-c-4f49f36b92a

**Comment by mackuba** [comment]
Yeah, this one works, thanks 👍

**Comment by njlr** [comment]
Closing this since the articles on hackernoon.com are out of our control. Seems like this is what you get for using Medium!
