### ISSUE TITLE
installing a package

### ISSUE THREAD

**Issue by jim4067** [LoopPerfect/buckaroo#370]
Installed buckaroo and was now in the process of installing a package but it just show this weird error below. 

`Error in Ln: 1 Col: 9
install ericniebler/range-v3
        ^
Expecting: end of input, '--cache-first' or '--verbose'`

 I have everything installed. My OS is Deepin and the default python system version is 2.7 but i also have 3 installed. should i change the python version to make it work or???????

**Comment by nikhedonia** [comment]
Hey thanks for taking Buckaroo for a spin!
packages are added via the `add` command followed by a URI eg.:
> buckaroo add github.com/buckaroo-pm/ericniebler-range-v3@branch=master

Python is not used by buckaroo but might be needed by one of the dependencies.
