### ISSUE TITLE
buck run :app is not working as it should. When I run the command (after quickstart) parsing of buck files and  building is successful. But after that instead of showing the output it shows "file not found : link" 

### ISSUE THREAD

**Issue by AyusDas** [LoopPerfect/buckaroo#372]

**Comment by nikhedonia** [comment]
Not able to reproduce, can we have more info about your system? - 
eg.: 
- OS
- buck version
- how did you install buck
- jvm version

I suspect that this is an issue with your buck installation

**Comment by AyusDas** [comment]
![Screenshot (100)](https://user-images.githubusercontent.com/45256705/83672366-c214cb00-a5f3-11ea-9c3f-47ac28ff4e9e.png)

The OS is windows 10
buck version: 2020.05.14.01
I installed buck using Chocolatey ( choco version 0.10.15 )

**Comment by AyusDas** [comment]
Okay, thanks.
