### ISSUE TITLE
buckaroo install emits wrong error message if git clone fails due to fs issues

### ISSUE THREAD

**Issue by nikhedonia** [LoopPerfect/buckaroo#42]
Buckaroo install $org/$mod $ver  will fail if folder  $org/$mod/$ver already exists  and is not a git controlled folder. However buckaroo complains that repository could not be fetched.

This happens if you touch $org/$mod/$ver before running install

error message:
```
java.io.IOException: java.io.IOException: org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /home/gaetano/Projects/buckaroo-tests/test2/buckaroo/oktal/pistache/0.0.1
```

**Comment by njlr** [comment]
Not relevant to Buckaroo Redux.
