### ISSUE TITLE
When did buck support c++ compilation on windows?

### ISSUE THREAD

**Issue by dyu** [LoopPerfect/buckaroo#53]
Tried buck a few months ago and cpp compilation on windows didn't work there yet.

**Comment by njlr** [comment]
Buck support for cxx on Windows is [very recent](https://github.com/facebook/buck/commit/8617a746f2cce396bf3e11f5d9a41869fdd3cb30), and requires some documentation. We will be writing a guide on this once we have ironed out the kinks. 

Buck/Buckaroo are ready to use on Linux and macOS, but I would hold off on Windows for now.

**Comment by njlr** [comment]
Our guide isn't quite ready yet, but there is an example repo for setting up Windows here: https://github.com/ilya-klyuchnikov/buck-windows-cxx
