### ISSUE TITLE
Buckaroo install failing

### ISSUE THREAD

**Issue by FictionIO** [LoopPerfect/buckaroo#74]
Hi,

I just installed Buckaroo (via Homebrew) and I'm trying to use it in a new project. When I try to add a dependency, it's throwing JsonSyntaxException and failing.  

OS: Mac 10.12.3
Buckaroo Version: 0.1.0

Steps to reproduce:
```
> mkdir test
> cd test
> buckaroo init
What is the name of your project? 
> test
Creating buckaroo.json... 
Done. 
> buckaroo install boost/thread
Adding dependency on boost/thread...
Could not read the config. 
java.io.IOException: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 8 column 2 path $.cookBooks

**Comment by ar90n** [comment]
Hi

I think it is odd because buckaroo works correctly in my environment like yours.
It seems that your log shows that buckaroo fails to parse config file.
So it might turn out well by removing $HOME/.buckaroo directory and reruning install.

**Comment by njlr** [comment]
Hi @FictionIO I'm also on macOS so will try to reproduce with a clean install.

**Comment by njlr** [comment]
@FictionIO I was unable to reproduce this issue on a clean install. 

As @ar90n suggested, it looks like your config file is invalid. There isn't much to this file, so I would suggest fixing it manually. 

After running an install, try copying the below into `~/.buckaroo/config.json`: 

```json=
{
  "cookBooks": [
    {
      "name": "buckaroo-recipes",
      "url": "git@github.com:loopperfect/buckaroo-recipes.git"
    }
  ],
  "analytics": "https://logging-nikhedonia.rhcloud.com/:80"
}
```

**Comment by FictionIO** [comment]
Apologies for the inconvenience. I didn't realise that I actually had an extra comma left in the config file after I removed the analytics line:

<pre>
{
  "cookBooks": [
    {
      "name": "buckaroo-recipes",
      "url": "git@github.com:loopperfect/buckaroo-recipes.git"
    }
  ]<b>,</b>
}
</pre>


Thank you.

**Comment by njlr** [comment]
Happens to the best of us!

The error message could definitely be better though. Issue here: https://github.com/LoopPerfect/buckaroo/issues/75
