### ISSUE TITLE
Support for platform_deps

### ISSUE THREAD

**Issue by nikhedonia** [LoopPerfect/buckaroo#99]

**Comment by njlr** [comment]
Demonstration of `platform_deps`: https://github.com/njlr/buck-platform-deps-example

**Comment by njlr** [comment]
For now, we can support this in the same way as dev-depedencies https://github.com/LoopPerfect/buckaroo/issues/31

**Comment by njlr** [comment]
Will be solved using https://github.com/LoopPerfect/buckaroo/issues/244
